sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t frostgod/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true frostgod/docker-react npm run test